#!/bin/sh

echo "Pre-commit starting"
echo "Ensuring core files are copied to root and are tracked..."

cp LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionViewController.* .
cp LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionView.* .
cp LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionItemView.* .
cp LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionRectView.* . 

git add .

echo "Pre-commit done"
