#!/bin/sh

echo "Copying files into root directory..."
cp ../../LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionViewController.* ../../
cp ../../LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionView.* ../../
cp ../../LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionItemView.* ../../
cp ../../LJSelectionViewDemo/LJSelectionViewDemo/LJSelectionRectView.* ../../

echo "Adding new files for Git to track..."
git add .
